### ISSUE TITLE
[AE-158] Allow test sketches to be outside examples folder

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-lint#588]
### Describe the request

The linter should allow for sketches outside of the `examples` folder to be within spec. Main reason, is to keep two types of `.ino` files seperate based on their functionality
- Example sketches -> These showcase the functionality of the library and have practical and/or pedagogical value
- Test sketches -> These are meant to strain the `compile-sketches.yml` workflow to the limit, as part of continuous testing (CT) procedures.

Including test sketches, which have no/little pedagogical value, will increase the complexity of the user experience. Advanced users can always see the test sketches in the repository or local installation of the library. 

### Describe the current behavior

According to Rule LD003, the linter does not allow for sketches outside the `examples` folder in the root directory of the library.

https://github.com/arduino/arduino-lint/blob/9363101bbb58d3cbed4066192f7c1c507763a296/internal/rule/ruleconfiguration/ruleconfiguration.go#L1308-L1311

### Arduino Lint version

arduino/arduino-lint-action@v1

### Operating system

N/A

### Operating system version

runs-on: ubuntu-latest

### Additional context

Running Linter via [check-arduino.yml](https://github.com/per1234/.github/blob/18100c7928dd8a37fb519820d06d43d366560385/workflow-templates/check-arduino.yml) workflow kindly provided by @per1234

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-lint/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Thanks for your suggestion, but the current configuration of the rule is as intended. If you want to add test sketches to the library, please put them under [the `extras` folder](https://arduino.github.io/arduino-cli/dev/library-specification/#extra-documentation) as suggested by the rule message.

There is a proposal for adding a dedicated folder for test files to the Arduino Library Specification:

https://github.com/arduino/arduino-cli/issues/990

However, the rule would only be adjusted if that proposal was accepted.
